name = "info-collector"
pages_build_output_dir = "./dist"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "info-collector-saves"
database_id = "122f1a20-6229-497c-a80a-0532be1a5867"
